### ISSUE TITLE
蓝牙wifi有点问题大佬

### ISSUE THREAD

**Issue by hfy123456** [AutismSuperman/Hackintosh-MSI-B460M-MORTAR-WIFI-i5-10400-RX6600XT#4]

**Comment by AutismSuperman** [comment]
对需要等 intel 网卡macos13适配后 才可以 要在等等

**Comment by kksxsyj** [comment]
蓝牙少了个驱动IntelBTPatcher.kext，[https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases](url)。WiFi我发现加载挺慢的，换成了itlwm+heliport一切正常了。

**Comment by kksxsyj** [comment]
> 蓝牙少了个驱动IntelBTPatcher.kext，[https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases](url)。WiFi我发现加载挺慢的，换成了itlwm+heliport一切正常了。

有点郁闷发现接力没了

**Comment by hfy123456** [comment]
> 

嗯嗯好的，等大佬更新，幸苦啦
